//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class LanguageManagerWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(LanguageManager), typeof(System.Object));
		L.RegFunction("GetInstance", GetInstance);
		L.RegFunction("Clear", Clear);
		L.RegFunction("GetValue", GetValue);
		L.RegFunction("Init", Init);
		L.RegFunction("New", _CreateLanguageManager);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _CreateLanguageManager(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 0)
			{
				LanguageManager obj = new LanguageManager();
				ToLua.PushObject(L, obj);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to ctor method: LanguageManager.New");
			}
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetInstance(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 0);
			LanguageManager o = LanguageManager.GetInstance();
			ToLua.PushObject(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Clear(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			LanguageManager obj = (LanguageManager)ToLua.CheckObject(L, 1, typeof(LanguageManager));
			obj.Clear();
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetValue(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			LanguageManager obj = (LanguageManager)ToLua.CheckObject(L, 1, typeof(LanguageManager));
			string arg0 = ToLua.CheckString(L, 2);
			string o = obj.GetValue(arg0);
			LuaDLL.lua_pushstring(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Init(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			LanguageManager obj = (LanguageManager)ToLua.CheckObject(L, 1, typeof(LanguageManager));
			obj.Init();
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

