//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class Singleton_SoundManagerWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(Singleton<SoundManager>), typeof(UnityEngine.MonoBehaviour), "Singleton_SoundManager");
		L.RegFunction("OnDestroy", OnDestroy);
		L.RegFunction("DestorySingleton", DestorySingleton);
		L.RegFunction("__eq", op_Equality);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.RegVar("Instance", get_Instance, null);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int OnDestroy(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			Singleton<SoundManager> obj = (Singleton<SoundManager>)ToLua.CheckObject(L, 1, typeof(Singleton<SoundManager>));
			obj.OnDestroy();
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int DestorySingleton(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 0);
			Singleton<SoundManager>.DestorySingleton();
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int op_Equality(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UnityEngine.Object arg0 = (UnityEngine.Object)ToLua.ToObject(L, 1);
			UnityEngine.Object arg1 = (UnityEngine.Object)ToLua.ToObject(L, 2);
			bool o = arg0 == arg1;
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Instance(IntPtr L)
	{
		try
		{
			ToLua.Push(L, Singleton<SoundManager>.Instance);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

