-- Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf/protobuf"
module('main_pb')


ITEM = protobuf.Descriptor();
local ITEM_ID_FIELD = protobuf.FieldDescriptor();
local ITEM_NUM_FIELD = protobuf.FieldDescriptor();
EQUIP = protobuf.Descriptor();
local EQUIP_ID_FIELD = protobuf.FieldDescriptor();
local EQUIP_BASEID_FIELD = protobuf.FieldDescriptor();
USER = protobuf.Descriptor();
local USER_ID_FIELD = protobuf.FieldDescriptor();
local USER_NAME_FIELD = protobuf.FieldDescriptor();
local USER_LV_FIELD = protobuf.FieldDescriptor();
local USER_EXP_FIELD = protobuf.FieldDescriptor();
local USER_CASH_FIELD = protobuf.FieldDescriptor();
local USER_COIN_FIELD = protobuf.FieldDescriptor();
local USER_ITEM_FIELD = protobuf.FieldDescriptor();
local USER_EQUIP_FIELD = protobuf.FieldDescriptor();

ITEM_ID_FIELD.name = "id"
ITEM_ID_FIELD.full_name = ".Item.id"
ITEM_ID_FIELD.number = 1
ITEM_ID_FIELD.index = 0
ITEM_ID_FIELD.label = 2
ITEM_ID_FIELD.has_default_value = false
ITEM_ID_FIELD.default_value = 0
ITEM_ID_FIELD.type = 5
ITEM_ID_FIELD.cpp_type = 1

ITEM_NUM_FIELD.name = "num"
ITEM_NUM_FIELD.full_name = ".Item.num"
ITEM_NUM_FIELD.number = 2
ITEM_NUM_FIELD.index = 1
ITEM_NUM_FIELD.label = 2
ITEM_NUM_FIELD.has_default_value = false
ITEM_NUM_FIELD.default_value = 0
ITEM_NUM_FIELD.type = 5
ITEM_NUM_FIELD.cpp_type = 1

ITEM.name = "Item"
ITEM.full_name = ".Item"
ITEM.nested_types = {}
ITEM.enum_types = {}
ITEM.fields = {ITEM_ID_FIELD, ITEM_NUM_FIELD}
ITEM.is_extendable = false
ITEM.extensions = {}
EQUIP_ID_FIELD.name = "id"
EQUIP_ID_FIELD.full_name = ".Equip.id"
EQUIP_ID_FIELD.number = 1
EQUIP_ID_FIELD.index = 0
EQUIP_ID_FIELD.label = 2
EQUIP_ID_FIELD.has_default_value = false
EQUIP_ID_FIELD.default_value = 0
EQUIP_ID_FIELD.type = 5
EQUIP_ID_FIELD.cpp_type = 1

EQUIP_BASEID_FIELD.name = "baseId"
EQUIP_BASEID_FIELD.full_name = ".Equip.baseId"
EQUIP_BASEID_FIELD.number = 2
EQUIP_BASEID_FIELD.index = 1
EQUIP_BASEID_FIELD.label = 2
EQUIP_BASEID_FIELD.has_default_value = false
EQUIP_BASEID_FIELD.default_value = 0
EQUIP_BASEID_FIELD.type = 5
EQUIP_BASEID_FIELD.cpp_type = 1

EQUIP.name = "Equip"
EQUIP.full_name = ".Equip"
EQUIP.nested_types = {}
EQUIP.enum_types = {}
EQUIP.fields = {EQUIP_ID_FIELD, EQUIP_BASEID_FIELD}
EQUIP.is_extendable = false
EQUIP.extensions = {}
USER_ID_FIELD.name = "id"
USER_ID_FIELD.full_name = ".User.id"
USER_ID_FIELD.number = 1
USER_ID_FIELD.index = 0
USER_ID_FIELD.label = 2
USER_ID_FIELD.has_default_value = false
USER_ID_FIELD.default_value = ""
USER_ID_FIELD.type = 9
USER_ID_FIELD.cpp_type = 9

USER_NAME_FIELD.name = "name"
USER_NAME_FIELD.full_name = ".User.name"
USER_NAME_FIELD.number = 2
USER_NAME_FIELD.index = 1
USER_NAME_FIELD.label = 2
USER_NAME_FIELD.has_default_value = false
USER_NAME_FIELD.default_value = ""
USER_NAME_FIELD.type = 9
USER_NAME_FIELD.cpp_type = 9

USER_LV_FIELD.name = "lv"
USER_LV_FIELD.full_name = ".User.lv"
USER_LV_FIELD.number = 3
USER_LV_FIELD.index = 2
USER_LV_FIELD.label = 2
USER_LV_FIELD.has_default_value = false
USER_LV_FIELD.default_value = 0
USER_LV_FIELD.type = 5
USER_LV_FIELD.cpp_type = 1

USER_EXP_FIELD.name = "exp"
USER_EXP_FIELD.full_name = ".User.exp"
USER_EXP_FIELD.number = 4
USER_EXP_FIELD.index = 3
USER_EXP_FIELD.label = 2
USER_EXP_FIELD.has_default_value = false
USER_EXP_FIELD.default_value = 0
USER_EXP_FIELD.type = 5
USER_EXP_FIELD.cpp_type = 1

USER_CASH_FIELD.name = "cash"
USER_CASH_FIELD.full_name = ".User.cash"
USER_CASH_FIELD.number = 5
USER_CASH_FIELD.index = 4
USER_CASH_FIELD.label = 2
USER_CASH_FIELD.has_default_value = false
USER_CASH_FIELD.default_value = 0
USER_CASH_FIELD.type = 5
USER_CASH_FIELD.cpp_type = 1

USER_COIN_FIELD.name = "coin"
USER_COIN_FIELD.full_name = ".User.coin"
USER_COIN_FIELD.number = 6
USER_COIN_FIELD.index = 5
USER_COIN_FIELD.label = 2
USER_COIN_FIELD.has_default_value = false
USER_COIN_FIELD.default_value = 0
USER_COIN_FIELD.type = 5
USER_COIN_FIELD.cpp_type = 1

USER_ITEM_FIELD.name = "item"
USER_ITEM_FIELD.full_name = ".User.item"
USER_ITEM_FIELD.number = 7
USER_ITEM_FIELD.index = 6
USER_ITEM_FIELD.label = 3
USER_ITEM_FIELD.has_default_value = false
USER_ITEM_FIELD.default_value = {}
USER_ITEM_FIELD.message_type = ITEM
USER_ITEM_FIELD.type = 11
USER_ITEM_FIELD.cpp_type = 10

USER_EQUIP_FIELD.name = "equip"
USER_EQUIP_FIELD.full_name = ".User.equip"
USER_EQUIP_FIELD.number = 8
USER_EQUIP_FIELD.index = 7
USER_EQUIP_FIELD.label = 3
USER_EQUIP_FIELD.has_default_value = false
USER_EQUIP_FIELD.default_value = {}
USER_EQUIP_FIELD.message_type = EQUIP
USER_EQUIP_FIELD.type = 11
USER_EQUIP_FIELD.cpp_type = 10

USER.name = "User"
USER.full_name = ".User"
USER.nested_types = {}
USER.enum_types = {}
USER.fields = {USER_ID_FIELD, USER_NAME_FIELD, USER_LV_FIELD, USER_EXP_FIELD, USER_CASH_FIELD, USER_COIN_FIELD, USER_ITEM_FIELD, USER_EQUIP_FIELD}
USER.is_extendable = false
USER.extensions = {}

Equip = protobuf.Message(EQUIP)
Item = protobuf.Message(ITEM)
User = protobuf.Message(USER)

